config_path: data/input/scenarios/siouxfalls-2014/config.xml
network_path: data/input/scenarios/siouxfalls-2014/Siouxfalls_network_PT.xml
schedule_path: data/input/scenarios/siouxfalls-2014/Siouxfalls_transitSchedule.xml
vehicle_path: data/input/scenarios/siouxfalls-2014/Siouxfalls_vehicles.xml

matsim_path: matsim/dist-2.9.0.jar
#matsim_path: matsim/my-fat-app-simple-run.jar

config_eval_path: config/config_eval.yaml

# route_set_path: data/input/R_KSP_routes.pkl
terminal_pairs_path: data/input/scenarios/siouxfalls-2014/terminal_pairs_set.json
type_of_bus: 'Bus MAN NL323F'
coordinate_system: "epsg:32633"
workers_input_path: data/input/worker
workers_output_path: data/output