matsim:
  bus_type:  # Marker for vehicle TYPE names in MATSim transit vehicle config
    - "bus"
  bus_transport_modes:    # Transport modes to filter for buses (matches any)
    - "bus"
    - "pt"

files:
  data: # These files are internal only. No need to change it
    bus_pax_records: "data/output/{{WORKER}}/eval/bus_pax_records"
    bus_delay_records: "data/output/{{WORKER}}/eval/bus_delay_records"
    trip_records: "data/output/{{WORKER}}/eval/trip_records"
    bus_trip_records: "data/output/{{WORKER}}/eval/bus_trip_records"

batch_size: 50000

scoring:
  params:
    coverage_radius: 400.0 # m
    early_headway_tolerance: 3.0 # minutes
    late_headway_tolerance: 3.0 # minutes
    travel_time_baseline: 54.121 # minutes
    productivity_baseline: 36.0 # passengers per service hour

  weights:
    # Set the weights for each scoring metric (0.0 to disable the metric). The weights must sum to 1.0.

    # Group 1: Service Availability (Spatial)
    transit_route_ratio: 0.0
    service_coverage: 0.0

    # Group 2: Economics & Ridership
    ridership: 1.0
    productivity: 0.0 # Note: There are recurring issues with productivity normalization. Recommend setting to 0.0 (disabled) until fixed.
    bus_efficiency: 0.0
    bus_effective_travel_dist: 0.0

    # Group 3: Travel Time
    travel_time: 0.0
    transit_auto_time_ratio: 0.0
    bus_transfer: 0.0

    # Group 4: Service Reliability
    on_time_performance: 0.0




